name: Node tests

on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: Lint & test
        run: |
          yarn install
          yarn test:ci
        env:
          CI: true
